services:

  # Конфигурация для всех сервисов  этого файла по умолчанию
  _defaults:
    autowire: true
    autoconfigure: true

  Casisdead2772\PostcodeBundle\Service\:
    resource: '../../Service/'
    public: true

  Casisdead2772\PostcodeBundle\Service\PublicApi\UK\postcodesApiService\PostcodesApiService:
    tags: ['casisdead2772.postcode.service']

  Casisdead2772\PostcodeBundle\PostcodeServiceManager:
    arguments:
      $services: !tagged casisdead2772.postcode.service

#  postcode.getter:
#    class: Casisdead2772\PostcodeBundle\Service\PostcodesService
#    arguments:
#      - '@monolog.http_client'
#    public: true
#
#  Casisdead2772\PostcodeBundle\Service\PostcodesService:
#    alias: postcode.getter
#    public: true

  postcode.getaddress:
    class: Casisdead2772\PostcodeBundle\Service\PrivateApi\UK\GetAddressApiService
    arguments:
      $apiKey: "%getaddress_apikey%"
    tags: ['casisdead2772.postcode.service']

  Casisdead2772\PostcodeBundle\Service\PrivateApi\UK\GetAddressApiService: '@postcode.getaddress'

  postcode.test:
    class: Casisdead2772\PostcodeBundle\Service\PrivateApi\UK\TestApi
    arguments:
      $apiKey: "?%test_apikey%"
    tags: [ 'casisdead2772.postcode.service' ]

  Casisdead2772\PostcodeBundle\Service\PrivateApi\UK\TestApi: '@postcode.test'


