services:

  # Конфигурация для всех сервисов  этого файла по умолчанию
  _defaults:

    autowire: true
    autoconfigure: true

  Casisdead2772\PostcodeBundle\Service\:
    resource: '../../Service/'
    public: true

  Casisdead2772\PostcodeBundle\Service\PublicApi\UK\postcodesApiService\PostcodesApiService:
    tags: ['casisdead2772.postcode.service']

#  Casisdead2772\PostcodeBundle\Service\PublicApi\UK\getaddressApiService\GetadressApiService:
#    tags: [ 'casisdead2772.postcode.service' ]

  Casisdead2772\PostcodeBundle\PostcodeServiceManager:
    arguments:
      $services: !tagged casisdead2772.postcode.service

#  postcode.getter:
#    class: Casisdead2772\PostcodeBundle\Service\PostcodesService
#    arguments:
#      - '@monolog.http_client'
#    public: true
#
#  Casisdead2772\PostcodeBundle\Service\PostcodesService:
#    alias: postcode.getter
#    public: true