services:

  # Конфигурация для всех сервисов  этого файла по умолчанию
  _defaults:
    autowire: true
    autoconfigure: true

  Casisdead2772\PostcodeBundle\Service\:
    resource: '../../Service/'
    public: true

  Casisdead2772\PostcodeBundle\PostcodeServiceManager:
    arguments:
      $services: !tagged casisdead2772.postcode.service

  Casisdead2772\PostcodeBundle\Service\PublicApi\UK\postcodesApiService\PostcodesApiService:
    tags: ['casisdead2772.postcode.service']

  postcode.getaddress:
    class: Casisdead2772\PostcodeBundle\Service\PrivateApi\UK\GetAddressApiService
    arguments:
      $apiKey: "%getaddress_apikey%"
    tags: ['casisdead2772.postcode.service']

  Casisdead2772\PostcodeBundle\Service\PrivateApi\UK\GetAddressApiService\GetAddressApiService: '@postcode.getaddress'


